[2024-06-05T09:02:45.233+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_dag.fetch_and_insert_into_elasticsearch_arrets_lignes manual__2024-06-05T09:02:44.360287+00:00 [queued]>
[2024-06-05T09:02:45.239+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_dag.fetch_and_insert_into_elasticsearch_arrets_lignes manual__2024-06-05T09:02:44.360287+00:00 [queued]>
[2024-06-05T09:02:45.239+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-05T09:02:45.376+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_and_insert_into_elasticsearch_arrets_lignes> on 2024-06-05 09:02:44.360287+00:00
[2024-06-05T09:02:45.379+0000] {standard_task_runner.py:57} INFO - Started process 1127 to run task
[2024-06-05T09:02:45.382+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'fetch_and_insert_into_elasticsearch_arrets_lignes', 'manual__2024-06-05T09:02:44.360287+00:00', '--job-id', '160', '--raw', '--subdir', 'DAGS_FOLDER/fetch_from_data_sources.py', '--cfg-path', '/tmp/tmpdvryydn7']
[2024-06-05T09:02:45.384+0000] {standard_task_runner.py:85} INFO - Job 160: Subtask fetch_and_insert_into_elasticsearch_arrets_lignes
[2024-06-05T09:02:45.409+0000] {task_command.py:415} INFO - Running <TaskInstance: my_python_dag.fetch_and_insert_into_elasticsearch_arrets_lignes manual__2024-06-05T09:02:44.360287+00:00 [running]> on host 9e4bf1cd7746
[2024-06-05T09:02:45.448+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_dag' AIRFLOW_CTX_TASK_ID='fetch_and_insert_into_elasticsearch_arrets_lignes' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T09:02:44.360287+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T09:02:44.360287+00:00'
[2024-06-05T09:02:45.449+0000] {logging_mixin.py:151} INFO - Hello from fetch data DAG
[2024-06-05T09:02:46.728+0000] {_transport.py:336} INFO - PUT https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443/stop-lines/_doc/618_IDFM%3A19593 [status:503 duration:0.368s]
[2024-06-05T09:02:46.730+0000] {_node_pool.py:246} WARNING - Node <Urllib3HttpNode(https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443)> has failed for 1 times in a row, putting on 1 second timeout
[2024-06-05T09:02:46.731+0000] {_transport.py:428} WARNING - Retrying request after non-successful status 503 (attempt 0 of 3)
[2024-06-05T09:02:46.842+0000] {_transport.py:336} INFO - PUT https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443/stop-lines/_doc/618_IDFM%3A19593 [status:503 duration:0.110s]
[2024-06-05T09:02:46.843+0000] {_node_pool.py:246} WARNING - Node <Urllib3HttpNode(https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443)> has failed for 2 times in a row, putting on 2 second timeout
[2024-06-05T09:02:46.843+0000] {_transport.py:428} WARNING - Retrying request after non-successful status 503 (attempt 1 of 3)
[2024-06-05T09:02:46.954+0000] {_transport.py:336} INFO - PUT https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443/stop-lines/_doc/618_IDFM%3A19593 [status:503 duration:0.110s]
[2024-06-05T09:02:46.955+0000] {_node_pool.py:246} WARNING - Node <Urllib3HttpNode(https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443)> has failed for 3 times in a row, putting on 4 second timeout
[2024-06-05T09:02:46.956+0000] {_transport.py:428} WARNING - Retrying request after non-successful status 503 (attempt 2 of 3)
[2024-06-05T09:02:47.067+0000] {_transport.py:336} INFO - PUT https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443/stop-lines/_doc/618_IDFM%3A19593 [status:503 duration:0.111s]
[2024-06-05T09:02:47.068+0000] {_node_pool.py:246} WARNING - Node <Urllib3HttpNode(https://e7bce3a6df364700956f06c04d5fc655.us-central1.gcp.cloud.es.io:443)> has failed for 4 times in a row, putting on 8 second timeout
[2024-06-05T09:02:47.069+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stations_functions.py", line 148, in fetch_and_insert_into_elasticsearch_arrets_lignes
    insert_into_elasticsearch_stop_lines(content)
  File "/opt/airflow/dags/stations_functions.py", line 142, in insert_into_elasticsearch_stop_lines
    client.index(index="stop-lines", id=unique_id, body=item)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 2318, in index
    return self.perform_request(  # type: ignore[return-value]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.ApiError: ApiError(503, "{'ok': False, 'message': 'The requested resource is currently unavailable.'}")
[2024-06-05T09:02:47.082+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=my_python_dag, task_id=fetch_and_insert_into_elasticsearch_arrets_lignes, execution_date=20240605T090244, start_date=20240605T090245, end_date=20240605T090247
[2024-06-05T09:02:47.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 160 for task fetch_and_insert_into_elasticsearch_arrets_lignes (ApiError(503, "{'ok': False, 'message': 'The requested resource is currently unavailable.'}"); 1127)
[2024-06-05T09:02:47.128+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-05T09:02:47.138+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
