[2024-06-06T15:01:06.526+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_dag.insert_into_elasticsearch_perimetre manual__2024-06-06T14:56:03.468097+00:00 [queued]>
[2024-06-06T15:01:06.530+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_dag.insert_into_elasticsearch_perimetre manual__2024-06-06T14:56:03.468097+00:00 [queued]>
[2024-06-06T15:01:06.531+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-06-06T15:01:06.617+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): insert_into_elasticsearch_perimetre> on 2024-06-06 14:56:03.468097+00:00
[2024-06-06T15:01:06.620+0000] {standard_task_runner.py:57} INFO - Started process 2659 to run task
[2024-06-06T15:01:06.622+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'insert_into_elasticsearch_perimetre', 'manual__2024-06-06T14:56:03.468097+00:00', '--job-id', '210', '--raw', '--subdir', 'DAGS_FOLDER/fetch_from_data_sources.py', '--cfg-path', '/tmp/tmpoaz2p5ut']
[2024-06-06T15:01:06.624+0000] {standard_task_runner.py:85} INFO - Job 210: Subtask insert_into_elasticsearch_perimetre
[2024-06-06T15:01:06.647+0000] {task_command.py:415} INFO - Running <TaskInstance: my_python_dag.insert_into_elasticsearch_perimetre manual__2024-06-06T14:56:03.468097+00:00 [running]> on host 9e4bf1cd7746
[2024-06-06T15:01:06.681+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_dag' AIRFLOW_CTX_TASK_ID='insert_into_elasticsearch_perimetre' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T14:56:03.468097+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T14:56:03.468097+00:00'
[2024-06-06T15:01:06.682+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: insert_into_elasticsearch_perim() missing 1 required positional argument: 'content'
[2024-06-06T15:01:06.686+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=my_python_dag, task_id=insert_into_elasticsearch_perimetre, execution_date=20240606T145603, start_date=20240606T150106, end_date=20240606T150106
[2024-06-06T15:01:06.692+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 210 for task insert_into_elasticsearch_perimetre (insert_into_elasticsearch_perim() missing 1 required positional argument: 'content'; 2659)
[2024-06-06T15:01:06.718+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-06T15:01:06.737+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
