[2024-06-06T15:00:51.196+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_dag.insert_into_elasticsearch_perimetre manual__2024-06-06T14:03:15.782700+00:00 [queued]>
[2024-06-06T15:00:51.453+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_dag.insert_into_elasticsearch_perimetre manual__2024-06-06T14:03:15.782700+00:00 [queued]>
[2024-06-06T15:00:51.454+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2024-06-06T15:00:51.467+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): insert_into_elasticsearch_perimetre> on 2024-06-06 14:03:15.782700+00:00
[2024-06-06T15:00:51.470+0000] {standard_task_runner.py:57} INFO - Started process 2649 to run task
[2024-06-06T15:00:51.476+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'insert_into_elasticsearch_perimetre', 'manual__2024-06-06T14:03:15.782700+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/fetch_from_data_sources.py', '--cfg-path', '/tmp/tmpvb358rhn']
[2024-06-06T15:00:51.480+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask insert_into_elasticsearch_perimetre
[2024-06-06T15:00:51.530+0000] {task_command.py:415} INFO - Running <TaskInstance: my_python_dag.insert_into_elasticsearch_perimetre manual__2024-06-06T14:03:15.782700+00:00 [running]> on host 9e4bf1cd7746
[2024-06-06T15:00:51.576+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_dag' AIRFLOW_CTX_TASK_ID='insert_into_elasticsearch_perimetre' AIRFLOW_CTX_EXECUTION_DATE='2024-06-06T14:03:15.782700+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-06T14:03:15.782700+00:00'
[2024-06-06T15:00:51.577+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: insert_into_elasticsearch_perim() missing 1 required positional argument: 'content'
[2024-06-06T15:00:51.586+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=my_python_dag, task_id=insert_into_elasticsearch_perimetre, execution_date=20240606T140315, start_date=20240606T150051, end_date=20240606T150051
[2024-06-06T15:00:51.592+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 208 for task insert_into_elasticsearch_perimetre (insert_into_elasticsearch_perim() missing 1 required positional argument: 'content'; 2649)
[2024-06-06T15:00:51.611+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-06T15:00:51.623+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
