[2024-06-05T08:40:32.712+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_python_dag.fetch_and_insert_into_elasticsearch_arrets_lignes manual__2024-06-05T08:40:31.855718+00:00 [queued]>
[2024-06-05T08:40:32.717+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_python_dag.fetch_and_insert_into_elasticsearch_arrets_lignes manual__2024-06-05T08:40:31.855718+00:00 [queued]>
[2024-06-05T08:40:32.717+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 2
[2024-06-05T08:40:32.808+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): fetch_and_insert_into_elasticsearch_arrets_lignes> on 2024-06-05 08:40:31.855718+00:00
[2024-06-05T08:40:32.811+0000] {standard_task_runner.py:57} INFO - Started process 783 to run task
[2024-06-05T08:40:32.813+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_python_dag', 'fetch_and_insert_into_elasticsearch_arrets_lignes', 'manual__2024-06-05T08:40:31.855718+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/fetch_from_data_sources.py', '--cfg-path', '/tmp/tmpdc616o_2']
[2024-06-05T08:40:32.815+0000] {standard_task_runner.py:85} INFO - Job 158: Subtask fetch_and_insert_into_elasticsearch_arrets_lignes
[2024-06-05T08:40:32.835+0000] {task_command.py:415} INFO - Running <TaskInstance: my_python_dag.fetch_and_insert_into_elasticsearch_arrets_lignes manual__2024-06-05T08:40:31.855718+00:00 [running]> on host 9e4bf1cd7746
[2024-06-05T08:40:32.868+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_python_dag' AIRFLOW_CTX_TASK_ID='fetch_and_insert_into_elasticsearch_arrets_lignes' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T08:40:31.855718+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T08:40:31.855718+00:00'
[2024-06-05T08:40:32.869+0000] {logging_mixin.py:151} INFO - Hello from fetch data DAG
[2024-06-05T08:40:33.612+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/stations_functions.py", line 135, in fetch_and_insert_into_elasticsearch_arrets_lignes
    insert_into_elasticsearch(content, "stop-lines")
  File "/opt/airflow/dags/stations_functions.py", line 105, in insert_into_elasticsearch
    unique_id = f"{item['id_gares']}_{item['nom_gares']}"
KeyError: 'id_gares'
[2024-06-05T08:40:33.616+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=my_python_dag, task_id=fetch_and_insert_into_elasticsearch_arrets_lignes, execution_date=20240605T084031, start_date=20240605T084032, end_date=20240605T084033
[2024-06-05T08:40:33.621+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 158 for task fetch_and_insert_into_elasticsearch_arrets_lignes ('id_gares'; 783)
[2024-06-05T08:40:33.646+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-06-05T08:40:33.655+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
